### ISSUE TITLE
'View'ing the results of a search cannot be modelled well in the schema

### ISSUE THREAD

**Issue by at055612** [gchq/event-logging-schema#10]
In situations where a user is viewing the results of a previous search, e.g. when the search results have been saved, the options available to model this with a `View` schema action are not ideal.  Currently under `View` you have 1..many of the MultiObjectComplexType objects, one of which is `SearchResult`.  `SearchResult` only really has `Relevancy` and `Data`, with no means of recording details of the items in that result set.

There is also ambiguity over whether `SearchResult` means a single items in a collection of results from a search, or the whole collection of items found in a single search.

**Comment by burnalting** [comment]
Can't one just use `View` of a  `Criteria` and make use of the `CriteraComplexType` to provide details of the original search and result set details?

**Comment by at055612** [comment]
See #11

**Comment by at055612** [comment]
Fixed in >v3.3.1
