### ISSUE TITLE
Add 'ElevatePrivilege'  to AuthenticateActionSimpleType

### ISSUE THREAD

**Issue by burnalting** [gchq/event-logging-schema#12]
When a user elevates their privilege on Linux, it should be considered as an Authentication activity. Although it could be modeled as a `Login`, I believe it would be better if it had is own action.

This may also mean we need to add a GroupComplexType choice to the Authenticate/{Device,User} choice as one can elevate their group privileges as well as user - see #13

We should also add an `Other` value as a catch-all. One can then use the EventDetail/Description element to advise what the `Other` value means for the given event.

**Comment by at055612** [comment]
Fixed
