### ISSUE TITLE
VersionSimpleType's enumeration attribute should be changed to 3.1.0 for the 3.1.0 version

### ISSUE THREAD

**Issue by burnalting** [gchq/event-logging-schema#18]
The restriction/enumeration value attribute should change from 3.0.0 to 3.1.0 or remove the enumeration.
IE Change
```
 <xs:simpleType name="VersionSimpleType">
        <xs:annotation>
            <xs:documentation>Type for specifying version numbers in a common way, e.g. 2.4</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]+(\.[0-9]+)*"/>
            <xs:enumeration value="3.0.0"/>
        </xs:restriction>
    </xs:simpleType>
```
to
```
 <xs:simpleType name="VersionSimpleType">
        <xs:annotation>
            <xs:documentation>Type for specifying version numbers in a common way, e.g. 2.4</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]+(\.[0-9]+)*"/>
            <xs:enumeration value="3.1.0"/>
        </xs:restriction>
    </xs:simpleType>
```

**Comment by burnalting** [comment]
Should we set the enumeration to have multiple values for the 3.x.x series of schemas? That way we are applying a generic restriction but against the series ... otherwise why have a single entry enumeration?

Thoughts?

**Comment by at055612** [comment]
After a discussion we agreed that a schema with version a.b.c should contain enumerations for all released versions that came before it with the same major version number, e.g. enumeration values that conform to:

major = a, minor <= b
