### ISSUE TITLE
Element to specify type of <Hash>

### ISSUE THREAD

**Issue by gcdev373** [gchq/event-logging-schema#3]
```<File>``` allows ```<Hash>``` but it is app/system specific what that means.

Perhaps an enum ```MD5|SHA-1|SHA-256| (some others?)|Other```

**Comment by burnalting** [comment]
Rather than an enum, have a HashType element as a string .. this allows for the user to be more explicit.

**Comment by at055612** [comment]
The only snag with allowing a free text string is keeping consistency, e.g. SHA-256/SHA 256/SHA256/sha-256/etc.  I agree it is preferable from an extensibility point of view.

**Comment by burnalting** [comment]
It's a trade off ... how quickly we can add enums to the schema verses the 'standard' types of hash strings that exist.

**Comment by at055612** [comment]
Fixed in >3.3.1
