### ISSUE TITLE
Add some concept of tagging/categorising objects described in the event

### ISSUE THREAD

**Issue by at055612** [gchq/event-logging-schema#31]
There is a need to be able to tag/categorise objects/data described in the schema.  It should be possible to associate an object under audit with multiple tags/categories and the tags/categories will likely be domain specific.  This is akin to adding tags to photos in Flickr or the topics associated with GitHub repositories.

**Comment by burnalting** [comment]
This is excellent, it means one can analyse access events based on an accessed object's thematic tags against say a person's corporate role.

**Comment by at055612** [comment]
Fixed in >3.3.1
