### ISSUE TITLE
Add xs:any Meta element to support extension/decoration of events

### ISSUE THREAD

**Issue by at055612** [gchq/event-logging-schema#35]
We need a way to allow the events or objects described in the events to be extended or decorated using content/structures described outside of the event-logging schema.  

For example #30 potentially requires events to be decorated with some concept of the veracity of an event.  The veracity could be described by its own XML schema (or some other data format) and the content included in a Meta element within the event.

**Comment by burnalting** [comment]
The only comment on this PR and #34 and #32 would be to enumerate the Crown Copyright years, perhaps change to 2016, 2017, 2018 or some such sequence.

**Comment by at055612** [comment]
Fixed in >3.3.1
