### ISSUE TITLE
Change documentation for LocationComplexType Timezone element

### ISSUE THREAD

**Issue by burnalting** [gchq/event-logging-schema#39]
Currently, the TimeZone element of LocationComplextType records

> Timezone pair for location in RFC3339 time-numoffset format separated by a slash '/' character. The first offset is for the location's standard timezone and the second for the daylight savings timezone. For example, Bristol, UK would be +00:00/+01:00

It is recommended that this changes to

> Timezone for location in ISO8601 Time zone designator format for the location at the time of the event. The format may be 'Z' for no offset from UTC,  '+hh:mm', '+hhmm' or '+hh' for a positive offset from UTC in hours and minutes or just hours or '-hh:mm' or '-hhmm' or '-hh' for a negative offset from UTC in  hours and minutes or just hours. Note that 'Z' can be represented as a positive zero offset from UTC i.e. '+00:00'

**Comment by at055612** [comment]
Fixed in >v3.3.1
