### ISSUE TITLE
Missing Data elements

### ISSUE THREAD

**Issue by burnalting** [gchq/event-logging-schema#4]
We should consider adding multiple Data elements for the Create, Delete, Network and View 'action' elements. All other 'actions' allow for multiple Data elements to carry additional information. These four are the only ones that don't. The only alternative is to place the 'action information' in Data elements of the 'subject of the action' (e.g. Object, Document, File, etc) which is NOT appropriate.

**Comment by burnalting** [comment]
Noted that the **Network** element can only have one of **Bind, Connect, Open, Close, Send, Recieve, Listen, Permit** or **Deny** and all are of type `NetworkComplexType` which already holds unbounded **Data** sub-elements.

So no need to change this element, only the `ObjectOutcomeComplexType` element type.

**Comment by at055612** [comment]
Fixed in v3.1.0
