### ISSUE TITLE
Extend the Enum for AuthenticateLogonTypeSimpleType

### ISSUE THREAD

**Issue by stroomdev10** [gchq/event-logging-schema#47]
Add: 
CachedRemoteInteractive
CachedUnlock
Proxy

**Comment by burnalting** [comment]
I would also suggest adding
`Other`
to allow for those we have not yet encountered. This way, if selected, one no doubt would add a Data element to the parent action that describes the type a'la

`<Data Name="OtherLogonType" Value="Whatever"/>`

I would also suggest that either the documentation for the schema adds explanations for the 3 + 1 additional values or add it to the AuthenticateLogonTypeSimpleType annotation/documentation element.

**Comment by burnalting** [comment]
Looks good.

**Comment by at055612** [comment]
Fixed in >v3.3.1
