### ISSUE TITLE
Need to record event source unique identified

### ISSUE THREAD

**Issue by burnalting** [gchq/event-logging-schema#56]
In many cases, an event source maintains a unique identifier (to the source capability). It is requested that we create an element to hold this source identifier.

It is suggest we use `Event/EventSource/SourceEventId` and this should be of type `xs:string`.

It is also suggested that users make use of an interim element `Event/EventSource/Data[@Name='EventSourceId']/@Value` and any future schema uplift (from one schema version to the next) translations apply this transform.

**Comment by at055612** [comment]
Covered by #58

**Comment by at055612** [comment]
Covered by EventSource/EventId available in v5.0
