### ISSUE TITLE
Add a Security Domain element to the SystemComplexType

### ISSUE THREAD

**Issue by burnalting** [gchq/event-logging-schema#68]
A system can reside in a `Security Domain` ... for example the the may be an instance of a  System in a `Secret` security domain and another instance in a `Official` domain. Equally, one could have domains of `Sales` , `Finance` and `Research`.

This allows to categorize the System itself.

This proposal suggests adding an element called `SecurityDomain` as a string.

Annotation could be `'An optional element to define the domain that the system exists in.'`

Please add between `Organisation` and `Version`.

**Comment by at055612** [comment]
``` xml
      <xs:element name="SecurityDomain" type="xs:string" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>An optional element to define the domain that the system exists in.</xs:documentation>
        </xs:annotation>
      </xs:element>
```
